@echo off

setlocal

set "BUILD_STATIC_LIBS=ON"
set "BUILD_SHARED_LIBS=OFF"
set "BUILD_CURL_EXE=OFF"
set "PICKY_COMPILER=OFF"
set "CMAKE_BUILD_TYPE=Debug"
set "_WIN32_WINNT=0x0601"

cmake -G "Unix Makefiles" . -DBUILD_STATIC_LIBS=%BUILD_STATIC_LIBS% -DBUILD_SHARED_LIBS=%BUILD_SHARED_LIBS% -DBUILD_CURL_EXE=%BUILD_CURL_EXE% -DPICKY_COMPILER=%PICKY_COMPILER% -S . -B out/build -DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE%

endlocal