@echo off

setlocal

set "BUILD_STATIC_LIBS=ON"
set "BUILD_SHARED_LIBS=OFF"
set "BUILD_CURL_EXE=OFF"
set "PICKY_COMPILER=OFF"
set "CMAKE_BUILD_TYPE=Debug"
set "_WIN32_WINNT=0x0601"

set -D CMAKE_MAKE_PROGRAM="C:\Program Files (x86)\GnuWin32\bin\make.exe"
set -D CMAKE_C_COMPILER="C:\msys64\ucrt64\bin\gcc.exe"


cmake -G "Unix Makefiles" . -DBUILD_STATIC_LIBS=%BUILD_STATIC_LIBS% -DBUILD_SHARED_LIBS=%BUILD_SHARED_LIBS% -DBUILD_CURL_EXE=%BUILD_CURL_EXE% -DPICKY_COMPILER=%PICKY_COMPILER% -S . -B out/build -DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE%

endlocal